services:
  web:
    build:
      target: production
    ports:
    - "80:80"
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
  dev:
    build:
      target: test
    environment:
      RUN_SANDBOX_TESTS: "true"
    profiles: [dev]
