services:
  web:
    build:
      target: production
    ports:
    - "80:80"
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
  dev:
    build:
      target: test
    cap_add:
    - SYSLOG
    profiles: [dev]
    ports:
      - "3000:3000"
