#ifndef USERS_WIRTSALTHOUSE_CODE_RUBY_MMIX_SIMULATOR_WASM_SRC_CONSTANTS_H
#define  USERS_WIRTSALTHOUSE_CODE_RUBY_MMIX_SIMULATOR_WASM_SRC_CONSTANTS_H

// limit input size to 100 KB
enum {
    MAX_BUFFER_SIZE = 100000
};

#endif
