export enum OpCode {
  TRAP = "TRAP",
  FCMP = "FCMP",
  FUN = "FUN",
  FEQL = "FEQL",
  FADD = "FADD",
  FIX = "FIX",
  FSUB = "FSUB",
  FIXU = "FIXU",

  FLOT = "FLOT",
  FLOTU = "FLOTU",
  SFLOT = "SFLOT",
  SFLOTU = "SFLOTU",

  FMUL = "FMUL",
  FCMPE = "FCMPE",
  FUNE = "FUNE",
  FEQLE = "FEQLE",
  FDIV = "FDIV",
  FSQRT = "FSQRT",
  FREM = "FREM",
  FINT = "FINT",

  MUL = "MUL",
  MULU = "MULU",
  DIV = "DIV",
  DIVU = "DIVU",

  ADD = "ADD",
  ADDU = "ADDU",
  SUB = "SUB",
  SUBU = "SUBU",

  _2ADDU = "2ADDU",
  _4ADDU = "4ADDU",
  _8ADDU = "8ADDU",
  _16ADDU = "16ADDU",

  CMP = "CMP",
  CMPU = "CMPU",
  NEG = "NEG",
  NEGU = "NEGU",

  SL = "SL",
  SLU = "SLU",
  SR = "SR",
  SRU = "SRU",

  BN = "BN",
  BZ = "BZ",
  BP = "BP",
  BOD = "BOD",

  BNN = "BNN",
  BNZ = "BNZ",
  BNP = "BNP",
  BEV = "BEV",

  PBN = "PBN",
  PBZ = "PBZ",
  PBP = "PBP",
  PBOD = "PBOD",

  PBNN = "PBNN",
  PBNZ = "PBNZ",
  PBNP = "PBNP",
  PBEV = "PBEV",

  CSN = "CSN",
  CSZ = "CSZ",
  CSP = "CSP",
  CSOD = "CSOD",

  CSNN = "CSNN",
  CSNZ = "CSNZ",
  CSNP = "CSNP",
  CSEV = "CSEV",

  ZSN = "ZSN",
  ZSZ = "ZSZ",
  ZSP = "ZSP",
  ZSOD = "ZSOD",

  ZSNN = "ZSNN",
  ZSNZ = "ZSNZ",
  ZSNP = "ZSNP",
  ZSEV = "ZSEV",

  LDB = "LDB",
  LDBU = "LDBU",
  LDW = "LDW",
  LDWU = "LDWU",

  LDT = "LDT",
  LDTU = "LDTU",
  LDO = "LDO",
  LDOU = "LDOU",

  LDSF = "LDSF",
  LDHT = "LDHT",
  CSWAP = "CSWAP",
  LDUNC = "LDUNC",

  LDVTS = "LDVTS",
  PRELD = "PRELD",
  PREGO = "PREGO",
  GO = "GO",

  STB = "STB",
  STBU = "STBU",
  STW = "STW",
  STWU = "STWU",

  STT = "STT",
  STTU = "STTU",
  STO = "STO",
  STOU = "STOU",

  STSF = "STSF",
  STHT = "STHT",
  STCO = "STCO",
  STUNC = "STUNC",

  SYNCD = "SYNCD",
  PREST = "PREST",
  SYNCID = "SYNCID",
  PUSHGO = "PUSHGO",

  OR = "OR",
  ORN = "ORN",
  NOR = "NOR",
  XOR = "XOR",

  AND = "AND",
  ANDN = "ANDN",
  NAND = "NAND",
  NXOR = "NXOR",

  BDIF = "BDIF",
  WDIF = "WDIF",
  TDIF = "TDIF",
  ODIF = "ODIF",

  MUX = "MUX",
  SADD = "SADD",
  MOR = "MOR",
  MXOR = "MXOR",

  SETH = "SETH",
  SETMH = "SETMH",
  SETML = "SETML",
  SETL = "SETL",
  INCH = "INCH",
  INCMH = "INCMH",
  INCML = "INCML",
  INCL = "INCL",

  ORH = "ORH",
  ORMH = "ORMH",
  ORML = "ORML",
  ORL = "ORL",
  ANDNH = "ANDNH",
  ANDNMH = "ANDNMH",
  ANDNML = "ANDNML",
  ANDNL = "ANDNL",

  JMP = "JMP",
  PUSHJ = "PUSHJ",
  GETA = "GETA",
  PUT = "PUT",

  POP = "POP",
  RESUME = "RESUME",
  SAVE = "SAVE",
  UNSAVE = "UNSAVE",
  SYNC = "SYNC",
  SWYM = "SWYM",
  GET = "GET",
  TRIP = "TRIP",

  LDA = "LDA",
}

export enum AssemblerDirective {
  LOC = "LOC",
  SET = "SET",
  BYTE = "BYTE",
  WYDE = "WYDE",
  TETRA = "TETRA",
  OCTA = "OCTA",
  GREG = "GREG",
  LOCAL = "LOCAL",
  BSPEC = "BSPEC",
  ESPEC = "ESPEC",
  IS = "IS",
  PREFIX = "PREFIX",
}
