name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

      - name: Scan for known security vulnerabilities in gems used
        run: bin/bundler-audit

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build and run tests in container
        run: |
          docker compose build rails-app
          docker compose run --rm rails-app bash -c "
              cd /workspaces/mmix-simulator &&
              bin/setup --skip-server &&
              bin/rails db:test:prepare test
          "

      - name: Tear down
        if: always()
        run: docker compose down

#  system-test:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v6

#      - name: Build and run system tests in container
#        env:
#          CAPYBARA_SERVER_PORT: "45678"
#          SELENIUM_HOST: selenium
#        run: |
#          docker compose build rails-app
#          docker compose run --rm --user vscode \
#            -e CAPYBARA_SERVER_PORT=45678 \
#            -e SELENIUM_HOST=selenium \
#            -e RAILS_ENV=test \
#            rails-app bash -c "
#              cd /workspaces/mmix-simulator &&
#              cp -r /home/vscode/.node_modules_cache node_modules &&
#              bin/setup --skip-server &&
#              bin/rails db:test:prepare test:system
#            "
#

#      - name: Keep screenshots from failed system tests
#        uses: actions/upload-artifact@v4
#        if: failure()
#        with:
#          name: screenshots
#          path: ${{ github.workspace }}/#tmp/screenshots
#          if-no-files-found: ignore

#      - name: Tear down
#        if: always()
#        run: docker compose down
